### ISSUE TITLE
Backquote macro

### ISSUE THREAD

**Issue by rvirding** [cnbbooks/lfe-tutorial#2]
Duncan I saw you are using the backquote macro in the example. While this is how would write it myself we haven't gone through backquote yet. Should we convert back to standard or go through macros before that? The erlang tutorial has very little on macros.

I know that in many of the classical lisp books they leave macros, at least writing them, until quite late. If we did that as well and did the example without backquote then we could use the bacquoted version as an example.

**Comment by rvirding** [comment]
Thinking a bit more about I think we should convert the example into not using the backquote, then when we do describe the backquote macro in the macro chapter we can use that function as an example of using backquote. How do you refer to another section/chapter?

**Comment by oubiwann** [comment]
Sounds good. You can refer to any link in the book like this:

```
[display text to be linked](section/page.html)
```

For example:

```
[Processes](concurrent/processes.html)
```

**Comment by rvirding** [comment]
Done. Now just need to write about the backquote macro.
